### PR TITLE
Create ci.yml

### PR DESCRIPTION
**Pull request by R4356th**
Adds GitHub Actions-based continuous integration system.

### CODE REVIEW

**Comment by R4356th** [comment]
Reopening to trigger GH Actions.

**Comment by R4356th** [comment]
Will need to revert #8.

**Comment by R4356th** [comment]
LGTM. What do you think, @GrahamSH-LLK?

**Comment by R4356th** [comment]
The warnings and errors can be safely ignored.

**Review by GrahamSH-LLK — APPROVED** [review]
Looks good!

**Pull request merged**
